//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogTable
    {
        public System.Guid TableID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> AuditFlag { get; set; }
    }
}
