//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrameWorkEntities : DbContext
    {
        public FrameWorkEntities()
            : base("name=FrameWorkEntities")
        {
    		Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checklist> Checklists { get; set; }
        public virtual DbSet<AuditActivityLog> AuditActivityLogs { get; set; }
        public virtual DbSet<AuditLogTable> AuditLogTables { get; set; }
        public virtual DbSet<AuditSecurityLog> AuditSecurityLogs { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CertAttachment> CertAttachments { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Dependant> Dependants { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EmployeeAttachemnt> EmployeeAttachemnts { get; set; }
        public virtual DbSet<EmployeeChecklist> EmployeeChecklists { get; set; }
        public virtual DbSet<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<FileTypeAttachment> FileTypeAttachments { get; set; }
        public virtual DbSet<PolicyAndMemo> PolicyAndMemoes { get; set; }
        public virtual DbSet<PromotionHistory> PromotionHistories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<UAMAction> UAMActions { get; set; }
        public virtual DbSet<UAMAppEmailTemplate> UAMAppEmailTemplates { get; set; }
        public virtual DbSet<UAMMailServer> UAMMailServers { get; set; }
        public virtual DbSet<UAMModule> UAMModules { get; set; }
        public virtual DbSet<UAMModuleAction> UAMModuleActions { get; set; }
        public virtual DbSet<UAMPlatform> UAMPlatforms { get; set; }
        public virtual DbSet<UAMPlatformLoginRole> UAMPlatformLoginRoles { get; set; }
        public virtual DbSet<UAMRoleModule> UAMRoleModules { get; set; }
        public virtual DbSet<UAMSendEmail> UAMSendEmails { get; set; }
        public virtual DbSet<UAMSendEmailStatu> UAMSendEmailStatus { get; set; }
        public virtual DbSet<UAMSMMEmailList> UAMSMMEmailLists { get; set; }
        public virtual DbSet<UAMSystem> UAMSystems { get; set; }
        public virtual DbSet<UAMUser> UAMUsers { get; set; }
        public virtual DbSet<UAMUserGroup> UAMUserGroups { get; set; }
        public virtual DbSet<UAMUserProfile> UAMUserProfiles { get; set; }
        public virtual DbSet<UAMUserRole> UAMUserRoles { get; set; }
        public virtual DbSet<UAMUserToken> UAMUserTokens { get; set; }
        public virtual DbSet<V_CategoryList> V_CategoryList { get; set; }
        public virtual DbSet<V_ChildModuleList> V_ChildModuleList { get; set; }
        public virtual DbSet<V_DepartmentList> V_DepartmentList { get; set; }
        public virtual DbSet<V_EmployeeAttachmentList> V_EmployeeAttachmentList { get; set; }
        public virtual DbSet<V_EmployeeProfileList> V_EmployeeProfileList { get; set; }
        public virtual DbSet<V_EmployeeReportingManagerList> V_EmployeeReportingManagerList { get; set; }
        public virtual DbSet<V_ModuleAction> V_ModuleAction { get; set; }
        public virtual DbSet<V_PolicyAndMemoList> V_PolicyAndMemoList { get; set; }
        public virtual DbSet<V_ProbationList> V_ProbationList { get; set; }
        public virtual DbSet<V_RegisteredEmployee> V_RegisteredEmployee { get; set; }
        public virtual DbSet<V_ReportingManager> V_ReportingManager { get; set; }
        public virtual DbSet<V_RoleMenuList> V_RoleMenuList { get; set; }
        public virtual DbSet<V_RoleModuleList> V_RoleModuleList { get; set; }
        public virtual DbSet<V_TeamList> V_TeamList { get; set; }
        public virtual DbSet<V_TrainingList> V_TrainingList { get; set; }
        public virtual DbSet<V_UAMUserGroup> V_UAMUserGroup { get; set; }
        public virtual DbSet<V_UserDetail> V_UserDetail { get; set; }
        public virtual DbSet<V_UserList> V_UserList { get; set; }
    }
}
