//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionHistory
    {
        public int ID { get; set; }
        public string PromotionTitle { get; set; }
        public System.DateTime PromotionDate { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual EmployeeProfile EmployeeProfile { get; set; }
    }
}
