//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMAppEmailTemplate
    {
        public System.Guid TempID { get; set; }
        public string TempSubject { get; set; }
        public string TempBody { get; set; }
        public int ToApplicant { get; set; }
        public int ToOfficer { get; set; }
        public string CreateDate { get; set; }
        public System.Guid CreateBy { get; set; }
        public string UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public string TempName { get; set; }
    }
}
