//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UAMModule()
        {
            this.UAMRoleModules = new HashSet<UAMRoleModule>();
        }
    
        public System.Guid ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public int ModuleStatus { get; set; }
        public Nullable<System.Guid> ParentModuleID { get; set; }
        public string ModuleLink { get; set; }
        public Nullable<int> DisplaySequence { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
        public Nullable<int> GroupSequence { get; set; }
        public string HTMLTagID { get; set; }
        public string HTMLTagIcon { get; set; }
        public Nullable<System.Guid> SystemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAMRoleModule> UAMRoleModules { get; set; }
        public virtual UAMSystem UAMSystem { get; set; }
    }
}
