//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMSMMEmailList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UAMSMMEmailList()
        {
            this.UAMUserProfiles = new HashSet<UAMUserProfile>();
        }
    
        public System.Guid EmailID { get; set; }
        public string RecipientName { get; set; }
        public string EmailAddress { get; set; }
        public int EmailStatus { get; set; }
        public decimal Deleted { get; set; }
        public string CreateDate { get; set; }
        public System.Guid AccessID { get; set; }
        public string BranchID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAMUserProfile> UAMUserProfiles { get; set; }
        public virtual UAMUser UAMUser { get; set; }
    }
}
