//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMSendEmail
    {
        public System.Guid SendEmailID { get; set; }
        public int SendStatus { get; set; }
        public int Deleted { get; set; }
        public string CreateDate { get; set; }
        public string CaseNumber { get; set; }
        public string EventDate { get; set; }
        public string ToEmail { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public Nullable<int> DBNo { get; set; }
        public string SenderAddress { get; set; }
        public string SenderName { get; set; }
    }
}
