//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMSendEmailStatu
    {
        public System.Guid SendEmailStatusID { get; set; }
        public string SendEmailID { get; set; }
        public int SendEmailStatus { get; set; }
        public int Deleted { get; set; }
        public string CreateDate { get; set; }
    }
}
