//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UAMSystem()
        {
            this.UAMModules = new HashSet<UAMModule>();
        }
    
        public System.Guid ID { get; set; }
        public string SystemName { get; set; }
        public string SystemLink { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAMModule> UAMModules { get; set; }
        public virtual UAMSystem UAMSystem1 { get; set; }
        public virtual UAMSystem UAMSystem2 { get; set; }
    }
}
