//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMUserProfile
    {
        public System.Guid UserProfileID { get; set; }
        public string StaffNumber { get; set; }
        public string StaffName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.Guid> EmailID { get; set; }
        public decimal UserProfileStatus { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
        public System.Guid AccessID { get; set; }
        public int Deleted { get; set; }
        public string BranchID { get; set; }
        public string PhoneNum { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> EmployeeProfileID { get; set; }
        public string ICNumber { get; set; }
        public string PassportNumber { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual UAMSMMEmailList UAMSMMEmailList { get; set; }
        public virtual UAMUser UAMUser { get; set; }
    }
}
