//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAMUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UAMUser()
        {
            this.UAMSMMEmailLists = new HashSet<UAMSMMEmailList>();
            this.UAMUserProfiles = new HashSet<UAMUserProfile>();
            this.UAMUserTokens = new HashSet<UAMUserToken>();
        }
    
        public System.Guid AccessID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public System.Guid RoleID { get; set; }
        public int AccessStatus { get; set; }
        public string CreateDate { get; set; }
        public string LastLoginDate { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.Guid> UserProfileID { get; set; }
        public string PswdExpiry { get; set; }
        public Nullable<int> NumInvalidLogin { get; set; }
        public Nullable<System.Guid> UserGroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAMSMMEmailList> UAMSMMEmailLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAMUserProfile> UAMUserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAMUserToken> UAMUserTokens { get; set; }
        public virtual UAMUserRole UAMUserRole { get; set; }
    }
}
