//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EmployeeAttachmentList
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string Filename { get; set; }
        public int FileTypeID { get; set; }
        public string StaffNumber { get; set; }
        public string EmployeeName { get; set; }
        public string TypeName { get; set; }
    }
}
