//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProbationList
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string StaffNumber { get; set; }
        public string EmailAddress { get; set; }
        public string PassportNumber { get; set; }
        public string ICNumber { get; set; }
        public Nullable<System.Guid> UserGroupID { get; set; }
        public string UserGroupName { get; set; }
        public System.Guid RoleID { get; set; }
        public string RoleName { get; set; }
        public string Designation { get; set; }
        public string TelNumber { get; set; }
        public string Religion { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string IncomeTaxNo { get; set; }
        public Nullable<int> BankName { get; set; }
        public string PersonalEmailAddress { get; set; }
        public string HighestAcademic { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Race { get; set; }
        public string EPFNo { get; set; }
        public string AccountNo { get; set; }
        public string HouseNo { get; set; }
        public string Nationality { get; set; }
        public string ECP1Name { get; set; }
        public string ECP1TelNumber { get; set; }
        public string ECP1HpNumber { get; set; }
        public string ECP1Relationship { get; set; }
        public string ECP2Name { get; set; }
        public string ECP2TelNumber { get; set; }
        public string ECP2HpNumber { get; set; }
        public string ECP2Relationship { get; set; }
        public string SpouseName { get; set; }
        public string SpouseIC { get; set; }
        public string SpousePassport { get; set; }
        public string SpouseOccupation { get; set; }
        public string SpouseTelNumber { get; set; }
        public string SpouseHpNumber { get; set; }
        public System.Guid ReportingManager { get; set; }
        public string ReportingManagerName { get; set; }
        public int Deleted { get; set; }
        public string PhotoUploadFile { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string ChineseName { get; set; }
        public string JobLevel { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<int> AccessStatus { get; set; }
    }
}
