//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserDetail
    {
        public System.Guid AccessID { get; set; }
        public string LoginID { get; set; }
        public int AccessStatus { get; set; }
        public string StaffNumber { get; set; }
        public string StaffName { get; set; }
        public System.Guid EmailID { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNum { get; set; }
        public string Designation { get; set; }
        public System.Guid RoleID { get; set; }
        public Nullable<System.Guid> UserGroupID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    }
}
