//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserList
    {
        public System.Guid AccessID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public System.Guid RoleID { get; set; }
        public int AccessStatus { get; set; }
        public string CreateDate { get; set; }
        public string LastLoginDate { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.Guid> UserProfileID { get; set; }
        public string PswdExpiry { get; set; }
        public Nullable<int> NumInvalidLogin { get; set; }
        public string StaffNumber { get; set; }
        public string StaffName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.Guid> EmailID { get; set; }
        public decimal UserProfileStatus { get; set; }
        public string UpdateDate { get; set; }
        public string BranchID { get; set; }
        public string PhoneNum { get; set; }
        public string RecipientName { get; set; }
        public string EmailAddress { get; set; }
        public int EmailStatus { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public int RoleStatus { get; set; }
        public Nullable<System.Guid> UserGroupID { get; set; }
    }
}
