//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFrameWorkLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebFrameWorkLib.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_FAILED.
        /// </summary>
        internal static string ADD_FAILED {
            get {
                return ResourceManager.GetString("ADD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_SUCCESS.
        /// </summary>
        internal static string ADD_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_EXIST.
        /// </summary>
        internal static string DATA_EXIST {
            get {
                return ResourceManager.GetString("DATA_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_FAILED.
        /// </summary>
        internal static string DELETE_FAILED {
            get {
                return ResourceManager.GetString("DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_SUCCESS.
        /// </summary>
        internal static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC_REGISTERED.
        /// </summary>
        internal static string IC_REGISTERED {
            get {
                return ResourceManager.GetString("IC_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_STAFFNO_REQUIRED.
        /// </summary>
        internal static string ID_STAFFNO_REQUIRED {
            get {
                return ResourceManager.GetString("ID_STAFFNO_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTITY_REGISTERED.
        /// </summary>
        internal static string IDENTITY_REGISTERED {
            get {
                return ResourceManager.GetString("IDENTITY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_DATA.
        /// </summary>
        internal static string NO_DATA {
            get {
                return ResourceManager.GetString("NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLDPWD_INCORRECT.
        /// </summary>
        internal static string OLDPWD_INCORRECT {
            get {
                return ResourceManager.GetString("OLDPWD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_UPDATED.
        /// </summary>
        internal static string PASSWORD_UPDATED {
            get {
                return ResourceManager.GetString("PASSWORD_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_FAILED.
        /// </summary>
        internal static string UPDATE_FAILED {
            get {
                return ResourceManager.GetString("UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_SUCCESS.
        /// </summary>
        internal static string UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_LOGOUT.
        /// </summary>
        internal static string USER_LOGOUT {
            get {
                return ResourceManager.GetString("USER_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_LOGOUT_FAILED.
        /// </summary>
        internal static string USER_LOGOUT_FAILED {
            get {
                return ResourceManager.GetString("USER_LOGOUT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_NOT_IN_EMPLOYEELIST.
        /// </summary>
        internal static string USER_NOT_IN_EMPLOYEELIST {
            get {
                return ResourceManager.GetString("USER_NOT_IN_EMPLOYEELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY_REGISTER_SUCCESS.
        /// </summary>
        internal static string VERIFY_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("VERIFY_REGISTER_SUCCESS", resourceCulture);
            }
        }
    }
}
