//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_FAILED.
        /// </summary>
        public static string ADD_FAILED {
            get {
                return ResourceManager.GetString("ADD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_SUCCESS.
        /// </summary>
        public static string ADD_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_SUCCESS_EMAIL_FAILED.
        /// </summary>
        public static string ADD_SUCCESS_EMAIL_FAILED {
            get {
                return ResourceManager.GetString("ADD_SUCCESS_EMAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_DUPLICATE.
        /// </summary>
        public static string DATA_DUPLICATE {
            get {
                return ResourceManager.GetString("DATA_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA_EXIST.
        /// </summary>
        public static string DATA_EXIST {
            get {
                return ResourceManager.GetString("DATA_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE_EXIST.
        /// </summary>
        public static string DATE_EXIST {
            get {
                return ResourceManager.GetString("DATE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE_FREEZED.
        /// </summary>
        public static string DATE_FREEZED {
            get {
                return ResourceManager.GetString("DATE_FREEZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE_NOT_VALID.
        /// </summary>
        public static string DATE_NOT_VALID {
            get {
                return ResourceManager.GetString("DATE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_FAILED.
        /// </summary>
        public static string DELETE_FAILED {
            get {
                return ResourceManager.GetString("DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_SUCCESS.
        /// </summary>
        public static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_SEND_FAILED.
        /// </summary>
        public static string EMAIL_SEND_FAILED {
            get {
                return ResourceManager.GetString("EMAIL_SEND_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_SEND_SUCCESS.
        /// </summary>
        public static string EMAIL_SEND_SUCCESS {
            get {
                return ResourceManager.GetString("EMAIL_SEND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE_NOT_FOUND.
        /// </summary>
        public static string EMPLOYEE_NOT_FOUND {
            get {
                return ResourceManager.GetString("EMPLOYEE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE_IS_REQUIRED.
        /// </summary>
        public static string FILE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("FILE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST_STATION_EXIST.
        /// </summary>
        public static string FIRST_STATION_EXIST {
            get {
                return ResourceManager.GetString("FIRST_STATION_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC_REGISTERED.
        /// </summary>
        public static string IC_REGISTERED {
            get {
                return ResourceManager.GetString("IC_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTITY_FAILED.
        /// </summary>
        public static string IDENTITY_FAILED {
            get {
                return ResourceManager.GetString("IDENTITY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTITY_REGISTERED.
        /// </summary>
        public static string IDENTITY_REGISTERED {
            get {
                return ResourceManager.GetString("IDENTITY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCORRECT_TIME.
        /// </summary>
        public static string INCORRECT_TIME {
            get {
                return ResourceManager.GetString("INCORRECT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_FILE_TYPE.
        /// </summary>
        public static string INVALID_FILE_TYPE {
            get {
                return ResourceManager.GetString("INVALID_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ROLE.
        /// </summary>
        public static string INVALID_ROLE {
            get {
                return ResourceManager.GetString("INVALID_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_USER.
        /// </summary>
        public static string INVALID_USER {
            get {
                return ResourceManager.GetString("INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX_BOOKING_DATE.
        /// </summary>
        public static string MAX_BOOKING_DATE {
            get {
                return ResourceManager.GetString("MAX_BOOKING_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX_LOAN_DATE.
        /// </summary>
        public static string MAX_LOAN_DATE {
            get {
                return ResourceManager.GetString("MAX_LOAN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_ATTACHMENT_UPLOADED.
        /// </summary>
        public static string NO_ATTACHMENT_UPLOADED {
            get {
                return ResourceManager.GetString("NO_ATTACHMENT_UPLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_DATA.
        /// </summary>
        public static string NO_DATA {
            get {
                return ResourceManager.GetString("NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_IDENTITY_DATA.
        /// </summary>
        public static string NO_IDENTITY_DATA {
            get {
                return ResourceManager.GetString("NO_IDENTITY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLDPWD_INCORRECT.
        /// </summary>
        public static string OLDPWD_INCORRECT {
            get {
                return ResourceManager.GetString("OLDPWD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD_UPDATED.
        /// </summary>
        public static string PASSWORD_UPDATED {
            get {
                return ResourceManager.GetString("PASSWORD_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAME_STATION.
        /// </summary>
        public static string SAME_STATION {
            get {
                return ResourceManager.GetString("SAME_STATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND_EMAIL_FAILED.
        /// </summary>
        public static string SEND_EMAIL_FAILED {
            get {
                return ResourceManager.GetString("SEND_EMAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_FAILED.
        /// </summary>
        public static string UPDATE_FAILED {
            get {
                return ResourceManager.GetString("UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_SUCCESS.
        /// </summary>
        public static string UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_LOGOUT.
        /// </summary>
        public static string USER_LOGOUT {
            get {
                return ResourceManager.GetString("USER_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_LOGOUT_FAILED.
        /// </summary>
        public static string USER_LOGOUT_FAILED {
            get {
                return ResourceManager.GetString("USER_LOGOUT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER_NOT_IN_EMPLOYEELIST.
        /// </summary>
        public static string USER_NOT_IN_EMPLOYEELIST {
            get {
                return ResourceManager.GetString("USER_NOT_IN_EMPLOYEELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID_MEMO_DATE.
        /// </summary>
        public static string VALID_MEMO_DATE {
            get {
                return ResourceManager.GetString("VALID_MEMO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY_REGISTER_SUCCESS.
        /// </summary>
        public static string VERIFY_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("VERIFY_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY_WHITE_SPACE.
        /// </summary>
        public static string VERIFY_WHITE_SPACE {
            get {
                return ResourceManager.GetString("VERIFY_WHITE_SPACE", resourceCulture);
            }
        }
    }
}
