//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppWatcher
    {
        public int ID { get; set; }
        public System.Guid Watcher_AccessID { get; set; }
        public System.Guid AppKey { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    }
}
