//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLibrary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemLibrary()
        {
            this.ItemLibraryAttachments = new HashSet<ItemLibraryAttachment>();
            this.ItemLibraryPendingUpdates = new HashSet<ItemLibraryPendingUpdate>();
            this.ItemLibraryPWPMappings = new HashSet<ItemLibraryPWPMapping>();
            this.ItemLibraryPWPMappings1 = new HashSet<ItemLibraryPWPMapping>();
            this.ItemLibrarySuppliers = new HashSet<ItemLibrarySupplier>();
            this.ItemLibraryTemps = new HashSet<ItemLibraryTemp>();
            this.ItemLibraryTempPWPMappings = new HashSet<ItemLibraryTempPWPMapping>();
            this.ItemLibraryTempPWPMappings1 = new HashSet<ItemLibraryTempPWPMapping>();
            this.ItemLibraryTempSuppliers = new HashSet<ItemLibraryTempSupplier>();
            this.UpdateTraces = new HashSet<UpdateTrace>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string IPN { get; set; }
        public string Manufacturer { get; set; }
        public string MPN { get; set; }
        public string ItemDescription { get; set; }
        public int RequiredSN { get; set; }
        public string Tariff { get; set; }
        public int RequiredCalibration { get; set; }
        public string MoreDetails { get; set; }
        public Nullable<System.Guid> Purchaser1 { get; set; }
        public Nullable<System.Guid> Purchaser2 { get; set; }
        public string KeyTechSpec { get; set; }
        public int IsDraft { get; set; }
        public int IsAddApproved { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.Guid> AppKey { get; set; }
        public string DeletedRemark { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryAttachment> ItemLibraryAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryPendingUpdate> ItemLibraryPendingUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryPWPMapping> ItemLibraryPWPMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryPWPMapping> ItemLibraryPWPMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibrarySupplier> ItemLibrarySuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryTemp> ItemLibraryTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryTempPWPMapping> ItemLibraryTempPWPMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryTempPWPMapping> ItemLibraryTempPWPMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLibraryTempSupplier> ItemLibraryTempSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateTrace> UpdateTraces { get; set; }
    }
}
