//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLibraryTempPWPMapping
    {
        public int ID { get; set; }
        public int Parent_ItemLibraryID { get; set; }
        public int PWP_ItemLibraryID { get; set; }
        public Nullable<decimal> PWP_UnitPriceDiscount { get; set; }
    
        public virtual ItemLibrary ItemLibrary { get; set; }
        public virtual ItemLibrary ItemLibrary1 { get; set; }
    }
}
