//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLibraryPendingUpdate
    {
        public int ID { get; set; }
        public int PendingUpdateActionID { get; set; }
        public int ItemLibraryID { get; set; }
        public string Remark { get; set; }
        public string ResponderRoles { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
    
        public virtual ItemLibrary ItemLibrary { get; set; }
        public virtual ItemLibraryPendingUpdateAction ItemLibraryPendingUpdateAction { get; set; }
    }
}
