//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class POItem
    {
        public int ID { get; set; }
        public int Sequence { get; set; }
        public int POID { get; set; }
        public Nullable<int> PR_ItemID { get; set; }
        public Nullable<int> ItemLibraryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ItemCode { get; set; }
        public string JobNo { get; set; }
        public string PrevJobNo { get; set; }
        public string IPN { get; set; }
        public string Manufacturer { get; set; }
        public string MPN { get; set; }
        public string ItemDescription { get; set; }
        public string MoreDetails { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Recv_Quantity { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceDiscount { get; set; }
        public Nullable<decimal> FinalUnitPrice { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<System.Guid> Requestor_AccessID { get; set; }
        public Nullable<System.DateTime> ReqETA { get; set; }
        public Nullable<System.DateTime> POReqETA { get; set; }
        public Nullable<System.DateTime> FirstCommitDate { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string Transferable { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> LocalTaxAmount { get; set; }
        public Nullable<decimal> LocalSubTotal { get; set; }
        public string Courier { get; set; }
        public string TrackingNo { get; set; }
    
        public virtual PO PO { get; set; }
    }
}
