//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateTrace
    {
        public int ID { get; set; }
        public int UpdateTraceTypeID { get; set; }
        public Nullable<int> UpdateTraceActionID { get; set; }
        public string UpdateRemark { get; set; }
        public Nullable<int> ItemLibraryID { get; set; }
        public Nullable<int> RFQID { get; set; }
        public Nullable<int> PRID { get; set; }
        public Nullable<int> POID { get; set; }
        public Nullable<int> ApprvOrReject { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    
        public virtual ItemLibrary ItemLibrary { get; set; }
        public virtual PO PO { get; set; }
        public virtual PR PR { get; set; }
        public virtual RFQ RFQ { get; set; }
        public virtual UpdateTraceAction UpdateTraceAction { get; set; }
        public virtual UpdateTraceType UpdateTraceType { get; set; }
    }
}
