//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ItemLibraryPWPMapping
    {
        public int Parent_ItemLibraryID { get; set; }
        public int PWP_ItemLibraryID { get; set; }
        public string IPN { get; set; }
        public string ItemDescription { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceDiscount { get; set; }
        public Nullable<decimal> PWP_UnitPriceDiscount { get; set; }
    }
}
