//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PH_PO
    {
        public string DOCNO { get; set; }
        public System.DateTime DOCDATE { get; set; }
        public System.DateTime POSTDATE { get; set; }
        public System.DateTime TAXDATE { get; set; }
        public string CODE { get; set; }
        public string COMPANYNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string PHONE1 { get; set; }
        public string MOBILE { get; set; }
        public string FAX1 { get; set; }
        public string ATTENTION { get; set; }
        public string AREA { get; set; }
        public string TERMS { get; set; }
        public string CURRENCYCODE { get; set; }
        public Nullable<decimal> CURRENCYRATE { get; set; }
        public string Description { get; set; }
        public decimal DOCAMT { get; set; }
        public decimal LOCALDOCAMT { get; set; }
        public string BRANCHNAME { get; set; }
        public string DADDRESS1 { get; set; }
        public string DADDRESS2 { get; set; }
        public string DADDRESS3 { get; set; }
        public string DADDRESS4 { get; set; }
        public string DATTENTION { get; set; }
        public string DPHONE1 { get; set; }
        public string DMOBILE { get; set; }
        public string DFAX1 { get; set; }
        public string Transferable { get; set; }
        public Nullable<int> UpdateCount { get; set; }
        public int IsDraft { get; set; }
        public int PO_StatusID { get; set; }
        public string JobNo { get; set; }
        public Nullable<System.Guid> Requestor_AccessID { get; set; }
        public string DeliveryTerm { get; set; }
        public string Validity { get; set; }
        public string Courier { get; set; }
        public string TrackingNo { get; set; }
        public string QuotationNo { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string Remark { get; set; }
    }
}
