//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRList_Watcher
    {
        public int PRID { get; set; }
        public Nullable<int> PRItemID { get; set; }
        public string PRNo { get; set; }
        public string JobNo { get; set; }
        public string Status { get; set; }
        public string IPN { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ReqETA { get; set; }
        public Nullable<System.DateTime> UpdateETA { get; set; }
        public Nullable<int> AcceptUpdateETA { get; set; }
        public string UpdateETA_PurchaserRemark { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> Purchaser1 { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<System.Guid> Watchers_AccessID { get; set; }
    }
}
