//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RFQUpdateTrace
    {
        public int ID { get; set; }
        public int UpdateTraceTypeID { get; set; }
        public Nullable<int> UpdateTraceActionID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public int RFQID { get; set; }
        public string UpdateRemark { get; set; }
        public string CreatedByStaffName { get; set; }
    }
}
