//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UpdateHistoryTrace
    {
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string Description { get; set; }
        public string UpdateRemark { get; set; }
        public Nullable<int> RFQID { get; set; }
        public Nullable<int> PRID { get; set; }
        public Nullable<int> POID { get; set; }
        public int UpdateTraceTypeID { get; set; }
        public string Status { get; set; }
        public string RFQNo { get; set; }
        public Nullable<System.Guid> Purchaser1 { get; set; }
        public Nullable<System.Guid> Purchaser2 { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> RFQCreatedDate { get; set; }
        public string CreatedByStaffName { get; set; }
        public Nullable<int> UpdateTraceActionID { get; set; }
    }
}
