//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watcher
    {
        public int ID { get; set; }
        public Nullable<int> PRID { get; set; }
        public Nullable<int> POID { get; set; }
        public Nullable<int> RFQID { get; set; }
        public System.Guid Watchers_AccessID { get; set; }
    
        public virtual RFQ RFQ { get; set; }
    }
}
